GeziRaberi/GeziRaberi/Controllers/UyeController.cs
using GeziRaberi.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace GeziRaberi.Controllers
{
    public class UyeController : Controller
    {
        // GET: Uye
        Context con = new Context();
        public ActionResult Index()
        {
            return View();
        }

        [Route("Uye-Giris")]
        public ActionResult UyeG()
        {
            return View();
        }
        [HttpPost]
        [Route("Uye-Giris")]
        public ActionResult UyeG(Admin uy)
        {
            var deyer = con.Admins.Where(x => x.KulaniciAdi == uy.KulaniciAdi
              && x.Password == uy.Password
              && x.IsActive == true
              && x.IsAdmin == false).FirstOrDefault();
            if(deyer!=null)
            {
                FormsAuthentication.SetAuthCookie(uy.KulaniciAdi, false);
                Session["UyeG"] = deyer.KulaniciAdi.ToString();
                return RedirectToAction("Index", "Default");
            }
            else
            {
                ViewBag.Error = "Hatalı Giriş";
                return View();
            }

        }

        [Route("Uye-Kayit")]
        public ActionResult UyeK()
        {
            return View();
        }
        [HttpPost]
        [Route("Uye-Kayit")]
        public ActionResult UyeK(Admin ka)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
            {
                string dAdi = Path.GetFileName(Request.Files[0].FileName);
                string duzanti = Path.GetExtension(Request.Files[0].FileName);
                string url = "~/Image/" + dAdi + duzanti;
                Request.Files[0].SaveAs(Server.MapPath(url));
                ka.Imge = "/Image/" + dAdi + duzanti;
            }
            ka.IsActive = true;
            ka.IsAdmin = false;
            con.Admins.Add(ka);
           
                con.SaveChanges();
                ViewBag.Message = "Mesahjınız başarılı Gönderilmiştir";
                return Redirect("/Uye-Giris");
            }
            else
            {
                ViewBag.Message = "Hatalı Bilğilerinizi ve Boş Alanları Kontrol Edin ";
                return View();
            }
          
        }

        public ActionResult Profilim()
        {
            string uy = HttpContext.User.Identity.Name;
            List<Admin> deyer = con.Admins.Where(x => x.KulaniciAdi == uy).ToList();
            return View(deyer);
        }


    }
}

GeziRaberi/GeziRaberi/Views/Uye/Profilim.cshtml
@model List<GeziRaberi.Models.Siniflar.Admin>
@{
    Layout = null;
}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Square Profile  with Flat Responsive widget Design :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Square Profile Widget a Flat Responsive Widget,Login form widgets, Sign up Web forms , Login signup Responsive web form,Flat Pricing table,Flat Drop downs,Registration Forms,News letter Forms,Elements" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href="~/web4/css/fontawesome-all.min.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/web4/css/style.css" rel='stylesheet' type='text/css' />

    <!--webfonts-->

    <link href="//fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <!--//webfonts-->

</head>
<body>

    <!-- main -->

    <div class="center-container">

        <div class="w3ls_banner_info">


            <h1>Sitemize Hoşgeldiniz 👋</h1>
            <div class="profile">
                <div class="wrap">
                    <div class="profile-main">
                        <div class="profile-pic wthree">
                            @foreach (var x in Model)
                            {
                                <img src="@x.Imge" alt="">
                                <h3>@x.AdSoyad</h3>
                            }
                            <div class="w3ls-agile-left">
                                <!---728x90--->

                                <ul class="address">
                                    <li>
                                        @foreach (var x in Model)
                                        {
                                            <ul class="address-text">
                                                <li><b>Kulanıcı Adı </b></li>
                                                <li>: </li>
                                                <li> <span class="w3">@x.KulaniciAdi</span></li>
                                            </ul>
                                        }
                                    </li>

                                    <li>
                                        @foreach (var x in Model)
                                        {
                                            <ul class="address-text">
                                                <li><b>Email Adresi </b></li>
                                                <li>: </li>
                                                <li> <span class="w3">@x.Mail</span></li>
                                            </ul>
                                        }
                                    </li>
                                    <li>
                                        @foreach (var x in Model)
                                        {
                                            <ul class="address-text">
                                                <li><b>PHONE </b></li>
                                                <li>: </li>
                                                <li> <span class="w3">@x.Telephone</span></li>
                                            </ul>
                                        }
                                    </li>


                                </ul>

                                <div class="clear"></div>
                            </div>
                        </div>

                        
                        <div class="clear"> </div>
                        <div class="profile-follows">

                            <div class="follow-btn">
                                <h3><a href="/Default/Index/">Ana Sayfaya Get</a></h3>
                            </div>
                            <div class="follow">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-google-plus-g"></i></a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>






            <!--footer-->
            <div class="footer-w3">
                <p>&copy; 2018 Square Profile Widget. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
            </div>
            <!--//footer-->

        </div>
    </div>
    <!-- //main -->

    <script src="js/jquery.min.v3.js"></script>
    <script src="js/jquery.circlechart.js"></script>
    <script>
        $('.demo-1').percentcircle();

        $('.demo-2').percentcircle({
            animate: false,
            diameter: 100,
            guage: 3,
            coverBg: '#000',
            bgColor: '#ff0000',
            fillColor: '#000',
            percentSize: '50px',
            percentWeight: 'normal'
        });


    </script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36251023-1']);
        _gaq.push(['_setDomainName', 'jqueryscript.net']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>



</body>
</html>

<style>
    img {
        width: 100px;
        height: 100px;
        border-radius: 100px;
    }

    .btn {
        width: 200px;
        height: 20px;
        text-align: center;
    }
</style>

GeziRaberi/GeziRaberi/Views/Uye/UyeG.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
<link href="~/loginstyle.css" rel="stylesheet" />
<div class="box">
    <h2>Üye Girişi</h2>
    <hr />
    <br />
    <br />
    @using (Html.BeginForm("UyeG", "Uye", FormMethod.Post))
    {
        @Html.TextBox("KulaniciAdi")
        <label><i class="fa fa-user" aria-hidden="true"></i> Kulanıcı Adı:</label>
        <br />
        <br />
        @Html.Password("Password")
        <label><i class="fa fa-lock" aria-hidden="true"></i> Şifre:</label>
        <br />
        <br />

        <button id="btg" class=" btn btn-outline-primary ">Giriş Yap</button>
    }
    <br />
    @{
        if (ViewBag.Message != null)
        {
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                <strong>@ViewBag.Message!</strong>
            </div>
        }
    }
</div>


<style>
    .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.5s;
    }

        .closebtn:hover {
            color: black;
        }
    body {
        margin: 0;
        padding: 0;
        background-image: url('../../Resim/ist.jpg');
        background-size:cover;
    }
    .box input {
        width: 100%;
        padding: 10px 0;
        font-size: 16px;
        color: #fff;
        letter-spacing: 1px;
        margin-bottom: 30px;
        border-radius: 20px;
        background: transparent;
        outline: none;
    }

    .box label {
        position: absolute;
        margin-top: -33px;
        left: 35px;
        padding: 10px 0;
        font-size: 16px;
        color: #0d9dbb;
        pointer-events: none;
    }

    #btg {
        width: 150px;
        font-size: 16px;
        background: transparent;
        border: none;
        outline: none;
        color: #0d9dbb;
        background: #fff;
        padding: 10px 20px;
        cursor: pointer;
        border-radius: 20px;
    }

        #btg:hover {
            color: #fff;
            background: #0d9dbb;
        }
</style>

GeziRaberi/GeziRaberi/Views/Uye/UyeK.cshtml
@model GeziRaberi.Models.Siniflar.Admin

@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>Hello, world!</title>
</head>
<body>
    <div class="box">
        @using (Html.BeginForm("UyeK", "Uye", FormMethod.Post, new { enctype = "multipart/form-Data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h2>Üye Kayıt Ol</h2>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.KulaniciAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KulaniciAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KulaniciAdi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AdSoyad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AdSoyad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Imge, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="Imge" />
                        @Html.ValidationMessageFor(model => model.Imge, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Kayit Ol" class="btn btn-outline-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
 
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->

</body>
</html>


<style>
    body {
        margin: 0;
        padding: 0;
        background-image: url('../../Resim/hot_air_balloon_ride_over_cappadocia_winter-wallpaper-960x540.jpg');
        background-size: cover;
    }
    .box {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        width: 500px;
        padding: 40px;
        justify-content: center;
        align-items: center;
        background: rgba(0,0,0,.8);
        box-shadow: 0 15px 25px rgb(0, 128, 255);
        border-left: 10px;
        transition: 0.5s;
    }

        .box:hover {
            -webkit-box-shadow: 0px 13px 60px 0px rgba(227,9,114,1);
            -moz-box-shadow: 0px 13px 60px 0px rgba(227,9,114,1);
            box-shadow: 0px 13px 60px 0px rgba(227,9,114,1);
        }

    label {
        color: #0d9dbb;
    }

    .box h2 {
        margin: 0 0 30px;
        padding: 0;
        color: #0d9dbb;
        text-align: center;
        font-size: 3rem;
        font-family: Georgia, serif;
    }
    .box hr {
        height: 1px;
        background: #0d9dbb;
    }
    .box .btn{
       width:150px;
       border:solid 1px rgb(0, 128, 255);
      
    }
</style>